added instll script

diff --git a/lib/rm/init b/lib/rm/init
--- a/lib/rm/init
+++ b/lib/rm/init
@@ -13,7 +13,7 @@ function rmInit () {
 	if requestingHelp || isNull $module; then
 		Usage "rm <module>" $empty $empty
 	else
-		coreRm $module false "bless_modules"
+		coreRm $module "package" "bless_modules"
 	fi
 }
 
@@ -21,15 +21,20 @@ function coreRm () {
 	declare local name="$1"
 	declare local type="$2"
 	declare local where="$3"
+	declare local __dirname="$BLESS_DIR/$where/$name"
+	declare local conf=$(resolveConf $name $where)
 
 	if hasItem "$name" "$where"; then
-		echo "Removing module ${name}.."
+		echo "rm: Removing ${type} ${name}.."
+		bless.IniParser $conf
+		bless.section.$type
+		if ! isNull "$remove"; then echo "rm:" $(eval $(echo $remove)); fi
 		removeItem "$name" $where
 		if test -f $BLESS_DIR/bin/$name; then
-			echo "Removing bin file 'bin/$name'.."
+			echo "rm: Removing bin file 'bin/$name'.."
 			rm $BLESS_DIR/bin/$name
 		fi
 	else
-		echo "Failed to remove '$name' in '$where'"
+		echo "rm: Failed to remove '$name' in '$where'"
 	fi
 }
